# Module 9: CI/CD Pipeline
name: Phishing Detection CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx scikit-learn pandas fastapi uvicorn prometheus-client

    - name: Run Model Training Test
      run: |
        # This would run a script that imports the train_model function and asserts the model file is created
        python -c "from phishing_system import train_model; train_model()"

    - name: Run Unit Tests
      run: |
        # In a real repo, you would run: pytest tests/
        echo "Running tests..."

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: user/phishing-detection:latest